default_context:
  project_name: 'FastAPI Template Project'
  project_slug: 'fastapi-template-project'
  domain_main: 'fastapi-template-project.com'
  domain_staging: 'stag.fastapi-template-project.com'
  docker_swarm_stack_name_main: 'fastapi-template-project-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-template-project-com'
  secret_key: 'ca9c1d4509ec6c9b9550fecfab3817a9b87e5e06bcbfe94298b12ce14ca8e428'
  first_superuser: 'admin@fastapi-template-project.com'
  first_superuser_password: '5d87bf6ee052598c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-template-project.com", "https://stag.fastapi-template-project.com", "https://fastapi-template-project.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-template-project.com'
  postgres_password: '13f15dd8a9157b23'
  pgadmin_default_user: 'admin@fastapi-template-project.com'
  pgadmin_default_user_password: '5d87bf6ee052598c'
  traefik_constraint_tag: 'fastapi-template-project.com'
  traefik_constraint_tag_staging: 'stag.fastapi-template-project.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:5d87bf6ee052598c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
