"""Initial schema

Revision ID: 0a925320a269
Revises: 
Create Date: 2020-12-06 17:40:36.027472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a925320a269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelName', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CAR', 'TRUCK', 'SPORT', name='cartype'), nullable=False),
    sa.Column('fuelType', sa.Enum('PETROL', 'DIESEL', 'HYBRID', 'EV', name='fueltype'), nullable=False),
    sa.Column('gearboxType', sa.Enum('AUTO', 'MANUAL', name='gearboxtype'), nullable=False),
    sa.Column('acType', sa.Enum('AUTO', 'MANUAL', name='actype'), nullable=False),
    sa.Column('numberOfPassengers', sa.Integer(), nullable=False),
    sa.Column('driveType', sa.Enum('FRONT', 'REAR', 'ALL_WHEELS', name='drivetype'), nullable=False),
    sa.Column('averageConsumption', sa.Float(), nullable=True),
    sa.Column('numberOfAirbags', sa.Integer(), nullable=False),
    sa.Column('bootCapacity', sa.Float(), nullable=True),
    sa.Column('pricePerDay', postgresql.MONEY(), nullable=False),
    sa.Column('depositAmount', postgresql.MONEY(), nullable=True),
    sa.Column('mileageLimit', sa.Float(), nullable=True),
    sa.Column('imageBase64', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_index(op.f('ix_car_modelName'), 'car', ['modelName'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_car_modelName'), table_name='car')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
