"""Add Customer model

Revision ID: 553b2730ca01
Revises: 5a4b0745deb7
Create Date: 2020-12-14 17:27:26.697867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '553b2730ca01'
down_revision = '5a4b0745deb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_customer_full_name'), 'customer', ['full_name'],
                    unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_full_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
