"""SportsCar schema

Revision ID: 5c4427d0d2f7
Revises: a142a8446da6
Create Date: 2020-12-07 21:25:02.173022

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c4427d0d2f7'
down_revision = 'a142a8446da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sportscar',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('horsepower', sa.Integer(), nullable=True),
                    sa.Column('zero_to_hundred_time', sa.Float(), nullable=True),
                    sa.Column('engine_capacity', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['car.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_sportscar_horsepower'), 'sportscar', ['horsepower'], unique=False)
    op.create_index(op.f('ix_sportscar_id'), 'sportscar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sportscar_id'), table_name='sportscar')
    op.drop_index(op.f('ix_sportscar_horsepower'), table_name='sportscar')
    op.drop_table('sportscar')
    # ### end Alembic commands ###
