"""Add Reservation model

Revision ID: a158de614e78
Revises: 553b2730ca01
Create Date: 2020-12-14 21:05:10.488922

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a158de614e78'
down_revision = '553b2730ca01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('car_id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.Enum('NEW', 'COMPLETED', 'CANCELLED',
                                                name='reservationstatus'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_id'), table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###
