"""Add Rental model

Revision ID: f449b0ab441f
Revises: 7c83a202986a
Create Date: 2020-12-16 14:07:53.196576

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f449b0ab441f'
down_revision = '7c83a202986a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('car_id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('reservation_id', sa.Integer(), nullable=True),
                    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED',
                                                name='rentalstatus'), nullable=False),
                    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_rental_id'), 'rental', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_id'), table_name='rental')
    op.drop_table('rental')
    # ### end Alembic commands ###
